[lint]
ignore = ["RUF012"]

[lint.per-file-ignores]
"**/migrations/*.py" = ["ALL"]
"**/admin.py" = ["RUF012"]
"pedidos/models.py" = ["RUF012"]
"proveedores/models.py" = ["RUF012"]
"tienda/migrations/*.py" = ["ALL"]
