# Generated by Django 6.0.6 on 2026-08-31 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='categorias/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('categoria_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategorias', to='catalogo.categoria')),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='colecciones/')),
                ('activa', models.BooleanField(default=True)),
                ('destacada', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Colección',
                'verbose_name_plural': 'Colecciones',
                'ordering': ['orden', 'nombre'],
                'indexes': [models.Index(fields=['slug'], name='catalogo_co_slug_440ff4_idx'), models.Index(fields=['activa'], name='catalogo_co_activa_255e83_idx'), models.Index(fields=['destacada'], name='catalogo_co_destaca_609b52_idx'), models.Index(fields=['orden'], name='catalogo_co_orden_6bb4c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('sku', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=False)),
                ('digital', models.BooleanField(default=False)),
                ('peso', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('alto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ancho', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('largo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalogo.categoria')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='proveedores.proveedor')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='MultimediaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video'), ('modelo3d', 'Modelo 3D'), ('documento', 'Documento')], default='imagen', max_length=20)),
                ('archivo', models.FileField(upload_to='catalogo/')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('texto_alternativo', models.CharField(blank=True, max_length=255)),
                ('principal', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Multimedia del producto',
                'verbose_name_plural': 'Multimedia de productos',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductoDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='productos_digitales/')),
                ('version', models.CharField(blank=True, max_length=50)),
                ('tamano_mb', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descargas_maximas', models.PositiveIntegerField(default=0, help_text='0 = ilimitadas')),
                ('dias_disponibles', models.PositiveIntegerField(default=0, help_text='0 = sin vencimiento')),
                ('requiere_licencia', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='producto_digital', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Producto digital',
                'verbose_name_plural': 'Productos digitales',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('color', models.CharField(default='#2563EB', help_text='Color hexadecimal (#RRGGBB).', max_length=7)),
                ('activa', models.BooleanField(default=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['slug'], name='catalogo_ta_slug_d6166e_idx'), models.Index(fields=['activa'], name='catalogo_ta_activa_33140f_idx'), models.Index(fields=['nombre'], name='catalogo_ta_nombre_a19113_idx')],
            },
        ),
        migrations.CreateModel(
            name='VarianteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('sku', models.CharField(max_length=80, unique=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('peso', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('activa', models.BooleanField(default=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Variante',
                'verbose_name_plural': 'Variantes',
                'ordering': ['producto', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('reserva', 'Reserva'), ('liberacion', 'Liberación'), ('devolucion', 'Devolución')], max_length=20)),
                ('cantidad', models.PositiveIntegerField()),
                ('stock_anterior', models.PositiveIntegerField()),
                ('stock_nuevo', models.PositiveIntegerField()),
                ('referencia', models.CharField(blank=True, max_length=120)),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_inventario', to='catalogo.varianteproducto')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-creado'],
            },
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['slug'], name='catalogo_ca_slug_84a82a_idx'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['activa'], name='catalogo_ca_activa_33ea23_idx'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['categoria_padre'], name='catalogo_ca_categor_d64adf_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['slug'], name='catalogo_pr_slug_17e2cc_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['sku'], name='catalogo_pr_sku_96594b_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo'], name='catalogo_pr_activo_05fd31_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['destacado'], name='catalogo_pr_destaca_c52bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria'], name='catalogo_pr_categor_8a569f_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['proveedor'], name='catalogo_pr_proveed_0f8ff5_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['precio'], name='catalogo_pr_precio_de346d_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['stock'], name='catalogo_pr_stock_583ff3_idx'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('precio__gte', 0)), name='producto_precio_positivo'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='producto_stock_positivo'),
        ),
        migrations.AddIndex(
            model_name='multimediaproducto',
            index=models.Index(fields=['producto'], name='catalogo_mu_product_bde31c_idx'),
        ),
        migrations.AddIndex(
            model_name='multimediaproducto',
            index=models.Index(fields=['tipo'], name='catalogo_mu_tipo_175d3b_idx'),
        ),
        migrations.AddIndex(
            model_name='multimediaproducto',
            index=models.Index(fields=['principal'], name='catalogo_mu_princip_030f1c_idx'),
        ),
        migrations.AddIndex(
            model_name='multimediaproducto',
            index=models.Index(fields=['activo'], name='catalogo_mu_activo_0ef67b_idx'),
        ),
        migrations.AddIndex(
            model_name='productodigital',
            index=models.Index(fields=['activa'], name='catalogo_pr_activa_71b4b6_idx'),
        ),
        migrations.AddIndex(
            model_name='productodigital',
            index=models.Index(fields=['version'], name='catalogo_pr_version_82e665_idx'),
        ),
        migrations.AddIndex(
            model_name='varianteproducto',
            index=models.Index(fields=['producto'], name='catalogo_va_product_458bf8_idx'),
        ),
        migrations.AddIndex(
            model_name='varianteproducto',
            index=models.Index(fields=['sku'], name='catalogo_va_sku_f92f9a_idx'),
        ),
        migrations.AddIndex(
            model_name='varianteproducto',
            index=models.Index(fields=['activa'], name='catalogo_va_activa_a106ff_idx'),
        ),
        migrations.AddIndex(
            model_name='varianteproducto',
            index=models.Index(fields=['stock'], name='catalogo_va_stock_fb57c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='varianteproducto',
            constraint=models.CheckConstraint(condition=models.Q(('precio__gte', 0)), name='variante_precio_positivo'),
        ),
        migrations.AddConstraint(
            model_name='varianteproducto',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='variante_stock_positivo'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['variante'], name='catalogo_mo_variant_2d1a5b_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['tipo'], name='catalogo_mo_tipo_ac53c2_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['creado'], name='catalogo_mo_creado_8d9fc8_idx'),
        ),
    ]
