# Generated by Django 6.0.6 on 2026-07-22 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=32, unique=True)),
                ('estado', models.CharField(choices=[('pendiente_pago', 'Pendiente de pago'), ('pagado', 'Pagado'), ('en_proceso', 'En proceso'), ('parcialmente_entregado', 'Parcialmente entregado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado'), ('reembolsado', 'Reembolsado'), ('cerrado', 'Cerrado')], default='pendiente_pago', max_length=30)),
                ('moneda', models.CharField(default='USD', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('envio_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impuesto_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('pagado_en', models.DateTimeField(blank=True, null=True)),
                ('cancelado_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelacion', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor_pago', models.CharField(choices=[('paypal', 'PayPal')], default='paypal', max_length=30)),
                ('estado', models.CharField(choices=[('creado', 'Creado'), ('pendiente', 'Pendiente'), ('autorizado', 'Autorizado'), ('capturado', 'Capturado'), ('fallido', 'Fallido'), ('cancelado', 'Cancelado'), ('reembolsado', 'Reembolsado'), ('parcialmente_reembolsado', 'Parcialmente reembolsado')], default='creado', max_length=30)),
                ('referencia_externa', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(default='USD', max_length=3)),
                ('respuesta_proveedor', models.JSONField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('confirmado_en', models.DateTimeField(blank=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
            },
        ),
        migrations.CreateModel(
            name='DireccionPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=30)),
                ('linea_1', models.CharField(max_length=255)),
                ('linea_2', models.CharField(blank=True, max_length=255)),
                ('ciudad', models.CharField(max_length=120)),
                ('departamento_estado', models.CharField(blank=True, max_length=120)),
                ('codigo_postal', models.CharField(blank=True, max_length=30)),
                ('pais', models.CharField(max_length=2)),
                ('referencia', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='direccion_envio', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'dirección de pedido',
                'verbose_name_plural': 'direcciones de pedido',
            },
        ),
        migrations.CreateModel(
            name='PedidoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('estado', models.CharField(choices=[('pendiente_pago', 'Pendiente de pago'), ('pagado', 'Pagado'), ('confirmado', 'Confirmado'), ('en_preparacion', 'En preparación'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado'), ('reembolsado', 'Reembolsado'), ('incidencia', 'Incidencia')], default='pendiente_pago', max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('envio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('monto_comision', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_proveedor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nota_cliente', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('preparado_en', models.DateTimeField(blank=True, null=True)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('entregado_en', models.DateTimeField(blank=True, null=True)),
                ('cancelado_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelacion', models.TextField(blank=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_proveedor', to='pedidos.pedido')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_proveedor', to='proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'pedido de proveedor',
                'verbose_name_plural': 'pedidos de proveedores',
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(max_length=200)),
                ('producto_descripcion', models.TextField(blank=True)),
                ('proveedor_nombre', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_pedido', to='catalogo.producto')),
                ('pedido_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='pedidos.pedidoproveedor')),
            ],
            options={
                'verbose_name': 'ítem de pedido',
                'verbose_name_plural': 'ítems de pedido',
            },
        ),
        migrations.CreateModel(
            name='EventoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cambio_estado', 'Cambio de estado'), ('pago', 'Pago'), ('sistema', 'Sistema'), ('nota', 'Nota')], default='sistema', max_length=30)),
                ('estado_anterior', models.CharField(blank=True, max_length=30)),
                ('estado_nuevo', models.CharField(blank=True, max_length=30)),
                ('comentario', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_pedido', to=settings.AUTH_USER_MODEL)),
                ('pedido_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='pedidos.pedidoproveedor')),
            ],
            options={
                'verbose_name': 'evento de pedido',
                'verbose_name_plural': 'eventos de pedido',
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['cliente', '-creado_en'], name='pedido_cliente_creado_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado', '-creado_en'], name='pedido_estado_creado_idx'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0), ('descuento_total__gte', 0), ('envio_total__gte', 0), ('impuesto_total__gte', 0), ('total__gte', 0)), name='pedido_importes_no_negativos'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['pedido', 'estado'], name='pago_pedido_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['proveedor_pago', 'estado', '-creado_en'], name='pago_conciliacion_idx'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gte', 0)), name='pago_monto_no_negativo'),
        ),
        migrations.AddIndex(
            model_name='pedidoproveedor',
            index=models.Index(fields=['proveedor', 'estado', '-creado_en'], name='pedprov_operacion_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidoproveedor',
            index=models.Index(fields=['estado', '-creado_en'], name='pedprov_estado_creado_idx'),
        ),
        migrations.AddConstraint(
            model_name='pedidoproveedor',
            constraint=models.UniqueConstraint(fields=('pedido', 'proveedor'), name='pedido_proveedor_unico'),
        ),
        migrations.AddConstraint(
            model_name='pedidoproveedor',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0), ('descuento_total__gte', 0), ('envio__gte', 0), ('impuesto__gte', 0), ('total__gte', 0), ('porcentaje_comision__gte', 0), ('monto_comision__gte', 0), ('monto_proveedor__gte', 0)), name='pedprov_importes_no_negativos'),
        ),
        migrations.AddIndex(
            model_name='itempedido',
            index=models.Index(fields=['pedido_proveedor'], name='itemped_proveedor_idx'),
        ),
        migrations.AddIndex(
            model_name='itempedido',
            index=models.Index(fields=['producto', '-creado_en'], name='itemped_producto_creado_idx'),
        ),
        migrations.AddConstraint(
            model_name='itempedido',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='itemped_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='itempedido',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0), ('subtotal__gte', 0)), name='itemped_importes_no_negativos'),
        ),
        migrations.AddIndex(
            model_name='eventopedido',
            index=models.Index(fields=['pedido_proveedor', '-creado_en'], name='evento_pedprov_creado_idx'),
        ),
    ]
