# Generated by Django 6.0.6 on 2026-07-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ('pedidos', '0001_initial'),
]

    operations = [
        migrations.RemoveConstraint(
            model_name='pedidoproveedor',
            name='pedprov_importes_no_negativos',
        ),
        migrations.AddField(
            model_name='direccionpedido',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='direccionpedido',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='direccionpedido',
            name='municipio',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='direccionpedido',
            name='provincia',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='direccionpedido',
            name='sector',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='pedidoproveedor',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pedidoproveedor',
            name='costo_logistico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pedidoproveedor',
            name='estado_logistico',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_preparacion', 'En preparación'), ('listo_despacho', 'Listo para despacho'), ('en_transito', 'En tránsito'), ('entregado', 'Entregado'), ('devuelto', 'Devuelto')], default='pendiente', max_length=30),
        ),
        migrations.AddField(
            model_name='pedidoproveedor',
            name='fecha_estimada_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidoproveedor',
            name='ganancia_unitux',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pedidoproveedor',
            name='numero_seguimiento',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='pedidoproveedor',
            name='transportista',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='pago',
            name='moneda',
            field=models.CharField(choices=[('USD', 'Dólar estadounidense'), ('DOP', 'Peso dominicano'), ('EUR', 'Euro'), ('MXN', 'Peso mexicano'), ('COP', 'Peso colombiano')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='pago',
            name='proveedor_pago',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('stripe', 'Stripe'), ('transferencia', 'Transferencia'), ('wallet', 'Wallet'), ('efectivo', 'Efectivo')], default='paypal', max_length=30),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='moneda',
            field=models.CharField(choices=[('USD', 'Dólar estadounidense'), ('DOP', 'Peso dominicano'), ('EUR', 'Euro'), ('MXN', 'Peso mexicano'), ('COP', 'Peso colombiano')], default='USD', max_length=3),
        ),
        migrations.AddIndex(
            model_name='pedidoproveedor',
            index=models.Index(fields=['estado_logistico', '-creado_en'], name='pedprov_logistica_idx'),
        ),
        migrations.AddConstraint(
            model_name='pedidoproveedor',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0), ('descuento_total__gte', 0), ('envio__gte', 0), ('impuesto__gte', 0), ('total__gte', 0), ('porcentaje_comision__gte', 0), ('monto_comision__gte', 0), ('monto_proveedor__gte', 0), ('costo_envio__gte', 0), ('costo_logistico__gte', 0)), name='pedprov_importes_no_negativos'),
        ),
    ]
