# Generated by Django 6.0.6 on 2026-08-31 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tienda', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='proveedores/logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='proveedores/banners/')),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('direccion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('bloqueado', 'Bloqueado'), ('rechazado', 'Rechazado')], db_index=True, default='pendiente', max_length=20)),
                ('comision', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('verificado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proveedor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre_tienda'],
                'indexes': [models.Index(fields=['estado'], name='proveedores_estado_96e4dc_idx'), models.Index(fields=['activo'], name='proveedores_activo_4d66a6_idx'), models.Index(fields=['verificado'], name='proveedores_verific_c89e70_idx')],
            },
        ),
    ]
